#!/usr/bin/python3
# Copyright 2022 Open Source Robotics Foundation, Inc. and Monterey Bay Aquarium Research Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Launch batch of buoy simulations."""

from em import invoke as empy
import numpy as np
import yaml

import os
import shutil
import subprocess
import sys
import time

from ament_index_python.packages import get_package_share_directory

from launch import LaunchDescription
from launch import LaunchService
from launch.actions import ExecuteProcess, IncludeLaunchDescription
from launch.actions import RegisterEventHandler
from launch.event_handlers import OnProcessExit, OnProcessStart

from launch.launch_description_sources import PythonLaunchDescriptionSource

from launch_testing.proc_info_handler import ActiveProcInfoHandler
from launch_testing.util import resolveProcesses

import rclpy
from rclpy.node import Node


DEFAULT_PHYSICS_MAX_STEP_SIZE = 0.01  # seconds


def spreading_factor_from_spotter_spread_deg(spread_deg):
    """
    Convert Spotter/SWIFT first-moment directional spread [deg]
    to the cos^(2s) spreading exponent `s`.

    Supports scalars or numpy arrays.
    """
    scalar_input = np.ndim(spread_deg) == 0
    spread_deg = np.asarray(spread_deg, dtype=float)

    if np.any(spread_deg < 0):
        raise ValueError("spread_deg must be >= 0 (use 0 to disable directional spreading)")

    max_spread_deg = np.degrees(np.sqrt(2.0))  # ~81.03 deg
    if np.any(spread_deg[spread_deg > 0] > max_spread_deg):
        raise ValueError(
            f"spread_deg must be <= {max_spread_deg:.3f} deg for this mapping"
        )

    # 0 degrees means no directional spreading; return None.
    if scalar_input and spread_deg.item() == 0.0:
        return None

    spread_rad = np.radians(spread_deg)
    return 2.0 / (spread_rad ** 2) - 1.0


def to_shape(a, shape):
    y_ = shape[0]
    y = a.shape[0]
    y_pad = (y_-y)
    return np.pad(a, (0, y_pad),
                  mode = 'constant', constant_values=a[-1])


class Controller(object):
    def __init__(self, package, launch_file):
        self.package = package
        self.launch_file = launch_file
    def __str__(self):
        return f'pkg:{self.package};launch_file:{self.launch_file}'


class MonoChromatic(object):
    def __init__(self, A, T):
        self.A, self.T = A, T
        self.name = 'MonoChromatic'

    def __str__(self):
        if self.A is not None:
            return f'{self.name};A:{self.A};T:{self.T}'
        else:
            return f'{self.name};A:default;T:default'


class Bretschneider(object):
    def __init__(self, Hs, Tp, n_phases=None, spreading_deg=None, spreading_factor=None):
        self.Hs, self.Tp = Hs, Tp
        self.n_phases = n_phases
        self.spreading_deg = spreading_deg
        self.spreading_factor = spreading_factor
        self.name = 'Bretschneider'

    def __str__(self):
        n_phases = int(self.n_phases) if self.n_phases is not None else 'default'
        spreading_deg = self.spreading_deg if self.spreading_deg is not None else 'default'
        spreading_factor = self.spreading_factor if self.spreading_factor is not None else 'default'
        if self.Hs is not None:
            return f'{self.name};Hs:{self.Hs};Tp:{self.Tp};' + \
                   f'n_phases:{n_phases};spreading_deg:{spreading_deg};' + \
                   f'spreading_factor:{spreading_factor}'
        else:
            return f'{self.name};Hs:default;Tp:default;' + \
                   f'n_phases:{n_phases};spreading_deg:{spreading_deg};' + \
                   f'spreading_factor:{spreading_factor}'


class Custom(object):
    def __init__(self, f, Szz):
        self.f, self.Szz = f, Szz
        self.name = 'Custom'

    def __str__(self):
        if self.f is not None:
            return f'{self.name};' + \
                   f'f:{":".join([str(f) for f in self.f])};' + \
                   f'Szz:{":".join([str(Szz) for Szz in self.Szz])}'
        else:
            return f'{self.name};f:defaults;Szz:defaults'


class SpringParams(object):
    def __init__(self, name, params):
        self.name = name
        self.params = params

    def __str__(self):
        if self.params is not None:
            return f'{self.name};' + \
                   f'{";".join([f"{p}:{v}" for p, v in zip(["n1", "n2", "P0", "V0", "T0"], self.params)])}'
        else:
            return f'{self.name};defaults'


class IncidentWaveHeightPoints(object):
    def __init__(self, points):
        self.points = points

    def __str__(self):
        if self.points is None:
            return 'default'
        return ';'.join([f'{x}:{y}' for x, y in self.points])


def generate_simulations(sim_params_yaml, rosbag2=True):

    rclpy.init()
    node = Node('mbari_wec_batch')

    with open(sim_params_yaml, 'r') as fd:
        sim_params = yaml.load(fd, Loader=yaml.CLoader)

    # don't print if param is None
    print_optional = lambda param: str(param) if param is not None else 'default'  # noqa: E731

    # Grab params from yaml

    ########################################
    # Batch-Specific (Non-Matrix) Parameters
    ########################################

    # physics real-time factor (RTF)
    try:
        if 'physics_rtf' in sim_params:
            physics_rtf = float(sim_params['physics_rtf'])
        else:
            physics_rtf = None
            node.get_logger().warn(
                'sim_params_yaml: optional physics_rtf parameter not specified -- defaulting'
            )
    except TypeError:
        node.get_logger().error('sim_params_yaml: physics_rtf parameter' +
                                ' must be a single value')
        sys.exit(-1)

    # Enable GUI
    try:
        if 'enable_gui' in sim_params:
            enable_gui = bool(sim_params['enable_gui'])
        else:
            enable_gui = False
            node.get_logger().debug(
                'sim_params_yaml: optional enable_gui parameter not specified' +
                ' -- defaulting to headless'
            )
    except TypeError:
        node.get_logger().error('sim_params_yaml: enable_gui parameter' +
                                ' must be a single value')
        sys.exit(-1)

    # duration (seconds)
    try:
        if 'duration' not in sim_params:
            node.get_logger().error('sim_params_yaml: required duration parameter not specified')
            sys.exit(-1)
        duration = float(sim_params['duration'])
    except TypeError:
        node.get_logger().error('sim_params_yaml: duration parameter' +
                                ' must be a single value in seconds')
        sys.exit(-1)

    # upper polytropic params: [n1,  # polytropic index for increasing volume
    #                           n2,  # polytropic index for decreasing volume
    #                           P0,  # Pressure (Pa) setpoint from polytropic PV curves
    #                           V0,  # Volume (m^3) setpoint from polytropic PV curves
    #                           T0]  # Temperature (K) setpoint for heat transfer
    if 'upper_spring_params' in sim_params:
        usp = np.array(sim_params['upper_spring_params'], dtype=float)
        usp = np.atleast_1d(usp)
        if usp.shape[0] != 5:
            node.get_logger().error(
                'sim_params_yaml: upper_spring_params must have 5 values -- n1, n2, P0, V0, T0'
            )
            sys.exit(-1)
    else:
        node.get_logger().warn(
            'sim_params_yaml: upper_spring_params parameter not specified -- defaulting'
        )
        usp = None

    # lower polytropic params: [n1,  # polytropic index for increasing volume
    #                           n2,  # polytropic index for decreasing volume
    #                           P0,  # Pressure (Pa) setpoint from polytropic PV curves
    #                           V0,  # Volume (m^3) setpoint from polytropic PV curves
    #                           T0]  # Temperature (K) setpoint for heat transfer
    if 'lower_spring_params' in sim_params:
        lsp = np.array(sim_params['lower_spring_params'], dtype=float)
        lsp = np.atleast_1d(lsp)
        if usp.shape[0] != 5:
            node.get_logger().error(
                'sim_params_yaml: lower_spring_params must have 5 values -- n1, n2, P0, V0, T0'
            )
            sys.exit(-1)
    else:
        node.get_logger().warn(
            'sim_params_yaml: lower_spring_params parameter not specified -- defaulting'
        )
        lsp = None

    ####################################
    # Run-Specific (Matrix) Parameters
    ####################################
    # seed (random seed for incident waves plugin)
    if 'seed' in sim_params:
        seeds = np.array(sim_params['seed'], dtype=int)
        seeds = np.atleast_1d(seeds)
    else:
        seeds = None
        node.get_logger().warn('sim_params_yaml: optional seed parameter not specified')

    # physics time step (seconds)
    if 'physics_step' in sim_params:
        physics_step = np.array(sim_params['physics_step'], dtype=float)
        physics_step = np.atleast_1d(physics_step)
    else:
        physics_step = [None]
        node.get_logger().warn(
            'sim_params_yaml: optional physics_step parameter not specified -- defaulting'
        )

    # door state ('open', 'closed')
    if 'door_state' in sim_params:
        door_state = sim_params['door_state']
        door_state = np.atleast_1d(door_state)
        if any(['open' not in ds and 'closed' not in ds for ds in door_state]):
            node.get_logger().error(
                "sim_params_yaml: all door_state parameters must be either 'open' or 'closed'"
            )
            sys.exit(-1)
    else:
        node.get_logger().warn(
            "sim_params_yaml: door_state parameter not specified -- defaulting to 'closed'"
        )
        door_state = ['closed']

    # scale factor (0.5 - 1.4)
    if 'scale_factor' in sim_params:
        scale_factor = np.array(sim_params['scale_factor'], dtype=float)
        scale_factor = np.atleast_1d(scale_factor)
        if not np.all((0.5 <= scale_factor) & (scale_factor <= 1.4)):
            node.get_logger().error(
                'sim_params_yaml: all scale_factor parameters must be between 0.5 to 1.4'
            )
            sys.exit(-1)
    else:
        node.get_logger().warn(
            'sim_params_yaml: scale_factor parameter not specified -- defaulting to 1.0'
        )
        scale_factor = [1.0]

    # Battery State
    # State of Charge (0.0 [270V] to 1.0 [320V])
    if 'battery_soc' in sim_params:
        battery_state = np.array(sim_params['battery_soc'], dtype=float)
        battery_state = np.atleast_1d(battery_state)
        if np.all((0.0 <= battery_state) & (battery_state <= 1.0)):
            batt_state_type = 'SoC'
        else:
            node.get_logger().error(
                'sim_params_yaml: all battery_soc parameters must be between 0.0 to 1.0'
            )
            sys.exit(-1)
    # EMF (270V to 320V)
    elif 'battery_emf' in sim_params:
        battery_state = np.array(sim_params['battery_emf'], dtype=float)
        battery_state = np.atleast_1d(battery_state)
        if np.all((270.0 <= battery_state) & (battery_state <= 320.0)):
            batt_state_type = 'EMF'
        else:
            node.get_logger().error(
                'sim_params_yaml: all battery_emf parameters must be between 300V to 270V'
            )
            sys.exit(-1)
    else:
        node.get_logger().warn(
            'sim_params_yaml: optional battery_emf or battery_soc parameter not specified'
        )
        battery_state = [None]
        batt_state_type = ''

    # mean_piston_position (meters)
    if 'mean_piston_position' in sim_params:
        mean_piston_position = np.array(sim_params['mean_piston_position'], dtype=float)
        mean_piston_position = np.atleast_1d(mean_piston_position)
    else:
        mean_piston_position = [None]
        node.get_logger().warn(
            'sim_params_yaml: optional mean_piston_position parameter not specified' + \
            ' -- defaulting'
        )

    # WaveDir: compass degrees True, waves coming FROM
    if 'wave_dir' in sim_params:
        wave_dir = np.array(sim_params['wave_dir'], dtype=float)
        wave_dir = np.atleast_1d(wave_dir)
    else:
        wave_dir = [None]

    # IncidentWaveHeightPoints: list of point sets, each with x/y arrays of equal length.
    if 'IncidentWaveHeightPoints' in sim_params:
        incident_wave_height_points = []
        try:
            point_sets = sim_params['IncidentWaveHeightPoints']
            if isinstance(point_sets, dict):
                point_sets = [point_sets]

            for point_set in point_sets:
                if not isinstance(point_set, dict):
                    raise TypeError

                if 'x' not in point_set or 'y' not in point_set:
                    node.get_logger().error(
                        'sim_params_yaml: IncidentWaveHeightPoints entries must define both x and y'
                    )
                    sys.exit(-1)

                x_vals = np.atleast_1d(np.array(point_set['x'], dtype=float))
                y_vals = np.atleast_1d(np.array(point_set['y'], dtype=float))
                if x_vals.shape != y_vals.shape:
                    node.get_logger().error(
                        'sim_params_yaml: IncidentWaveHeightPoints: x and y have different length'
                    )
                    sys.exit(-1)

                incident_wave_height_points.append(
                    IncidentWaveHeightPoints([[float(x), float(y)]
                                              for x, y in zip(x_vals, y_vals)])
                )
        except TypeError:
            node.get_logger().error(
                'sim_params_yaml: IncidentWaveHeightPoints must be a mapping or list of mappings '
                + 'with x/y arrays'
            )
            sys.exit(-1)
    else:
        incident_wave_height_points = [None]

    if 'controller' in sim_params:
        controller_params = sim_params['controller']
        controllers = []
        for controller in controller_params:
            controllers.append(Controller(**controller))
    else:
        controllers = [None]
        node.get_logger().warn(
            'sim_params_yaml: optional controller parameter not specified -- assuming None'
        )

    # IncWaveSpectrumType
    if 'IncidentWaveSpectrumType' in sim_params:
        inc_wave_spectrum_types = sim_params['IncidentWaveSpectrumType']
        incident_waves = []
        for inc_wave_spectrum_type in inc_wave_spectrum_types:
            if 'MonoChromatic' in inc_wave_spectrum_type:
                try:
                    monochromatic_spectrum = inc_wave_spectrum_type['MonoChromatic']
                except TypeError:  # just default params
                    monochromatic_spectrum = {}
                if 'A' in monochromatic_spectrum:
                    A = np.array(monochromatic_spectrum['A'], dtype=float)
                    A = np.atleast_1d(A)
                else:
                    A = None
                if 'T' in monochromatic_spectrum:
                    T = np.array(monochromatic_spectrum['T'], dtype=float)
                    T = np.atleast_1d(T)
                else:
                    T = None

                if (A is None) ^ (T is None):
                    node.get_logger().error(
                        'sim_params_yaml: MonoChromatic: A or T unspecified.' +
                        ' Please specify both or neither'
                    )
                    sys.exit(-1)
                if A.shape != T.shape:
                    node.get_logger().error(
                        'sim_params_yaml: MonoChromatic: A and T have different length'
                    )
                    sys.exit(-1)
                incident_waves.extend([MonoChromatic(a, t) for a, t in zip(A, T)])
            elif 'Bretschneider' in inc_wave_spectrum_type:
                try:
                    bretschneider_spectrum = inc_wave_spectrum_type['Bretschneider']
                except TypeError:  # just default params
                    bretschneider_spectrum = {}
                if 'Hs' in bretschneider_spectrum:
                    Hs = np.array(bretschneider_spectrum['Hs'], dtype=float)
                    Hs = np.atleast_1d(Hs)
                else:
                    Hs = None
                if 'Tp' in bretschneider_spectrum:
                    Tp = np.array(bretschneider_spectrum['Tp'], dtype=float)
                    Tp = np.atleast_1d(Tp)
                else:
                    Tp = None
                if 'n_phases' in bretschneider_spectrum:
                    n_phases = np.array(bretschneider_spectrum['n_phases'], dtype=int)
                    n_phases = np.atleast_1d(n_phases)
                else:
                    n_phases = None
                if 'spreading_deg' in bretschneider_spectrum:
                    spreading_deg = np.array(bretschneider_spectrum['spreading_deg'], dtype=float)
                    spreading_deg = np.atleast_1d(spreading_deg)
                else:
                    spreading_deg = None

                if (Hs is None) ^ (Tp is None):
                    node.get_logger().error(
                        'sim_params_yaml: Bretschneider: Hs or Tp unspecified.' +
                        ' Please specify both or neither'
                    )
                    sys.exit(-1)
                if Hs.shape != Tp.shape:
                    node.get_logger().error(
                        'sim_params_yaml: Bretschneider: Hs and Tp have different length.'
                    )
                    sys.exit(-1)

                if n_phases is None:
                    n_phases = np.full(Hs.shape, None, dtype=object)
                elif n_phases.size == 1 and Hs.size > 1:
                    n_phases = np.full(Hs.shape, int(n_phases.item()), dtype=int)
                elif n_phases.shape != Hs.shape:
                    node.get_logger().error(
                        'sim_params_yaml: Bretschneider: n_phases must be scalar or match Hs/Tp length.'
                    )
                    sys.exit(-1)

                if spreading_deg is None:
                    spreading_deg = np.full(Hs.shape, None, dtype=object)
                elif spreading_deg.size == 1 and Hs.size > 1:
                    spreading_deg = np.full(Hs.shape, float(spreading_deg.item()), dtype=float)
                elif spreading_deg.shape != Hs.shape:
                    node.get_logger().error(
                        'sim_params_yaml: Bretschneider: spreading_deg must be scalar or match Hs/Tp length.'
                    )
                    sys.exit(-1)

                spreading_factor = np.full(Hs.shape, None, dtype=object)
                # spread_mask: non-None and non-zero spreading_deg values get converted
                # spreading_deg=0 stays as spreading_factor=None → no directional spreading
                spread_mask = np.array(
                    [sd is not None and float(sd) != 0.0 for sd in spreading_deg], dtype=bool
                )
                if np.any(spread_mask):
                    try:
                        spreading_factor[spread_mask] = spreading_factor_from_spotter_spread_deg(
                            np.array(spreading_deg[spread_mask], dtype=float)
                        )
                    except ValueError as exc:
                        node.get_logger().error(f'sim_params_yaml: Bretschneider: {exc}')
                        sys.exit(-1)

                incident_waves.extend([
                    Bretschneider(hs, tp, np_, sd, sf)
                    for hs, tp, np_, sd, sf in zip(Hs, Tp, n_phases,
                                                   spreading_deg, spreading_factor)
                ])
            elif 'Custom' in inc_wave_spectrum_type:
                try:
                    custom_spectrum = inc_wave_spectrum_type['Custom']
                except TypeError:  # just default params
                    custom_spectrum = {}
                if 'f' in custom_spectrum:
                    f = np.array(custom_spectrum['f'], dtype=float)
                    f = np.atleast_1d(f)
                else:
                    f = None
                if 'Szz' in custom_spectrum:
                    Szz = np.array(custom_spectrum['Szz'], dtype=float)
                    Szz = np.atleast_1d(Szz)
                else:
                    Szz = None

                if (f is None) ^ (Szz is None):
                    node.get_logger().error(
                        'sim_params_yaml: Custom: f or Szz unspecified.' +
                        ' Please specify both or neither'
                    )
                    sys.exit(-1)
                if f is not None and Szz is not None:
                    if f.shape != Szz.shape:
                        node.get_logger().error(
                            'sim_params_yaml: Custom: f.shape != Szz.shape'
                        )
                        sys.exit(-1)
                incident_waves.append(Custom(f, Szz))
            else:
                node.get_logger().error(
                    f'sim_params_yaml: IncWaveSpectrumType [{inc_wave_spectrum_type}]' +
                    ' did not match supported types:\n    ' +
                    '\n    '.join(['MonoChromatic', 'Bretschneider', 'Custom'])
                )
                sys.exit(-1)
    else:
        node.get_logger().warn(
            'sim_params_yaml: optional IncWaveSpectrumType parameter not specified' +
            ' -- defaulting to No Waves'
        )
        incident_waves = [None]

    # create batch results directory
    timestr = time.strftime("%Y%m%d%H%M%S")
    batch_results_dir = f'batch_results_{timestr}'
    node.get_logger().info(f'Creating batch results directory: {batch_results_dir}')
    os.makedirs(batch_results_dir)
    # python workaround for 'ln -sf'
    os.symlink(batch_results_dir, f'latest_batch_results_{timestr}', target_is_directory=True)
    os.replace(f'latest_batch_results_{timestr}', 'latest_batch_results')

    sim_params_name, dot_yaml = os.path.splitext(os.path.basename(sim_params_yaml))
    sim_params_date_yaml = sim_params_name + f'_{timestr}' + dot_yaml
    node.get_logger().debug('Copying sim params yaml to batch results directory: ' +
                            os.path.join(batch_results_dir,
                                         sim_params_date_yaml))
    shutil.copy(sim_params_yaml,
                os.path.join(batch_results_dir,
                             sim_params_date_yaml))

    if 'matrix_mode' not in sim_params or \
      ('matrix_mode' in sim_params and sim_params['matrix_mode']):
        # generate test matrix
        batch_params = list(zip(*[param.ravel() for param in np.meshgrid(seeds,
                                                                         physics_step,
                                                                         door_state,
                                                                         scale_factor,
                                                                         battery_state,
                                                                         mean_piston_position,
                                                                         wave_dir,
                                                                         incident_wave_height_points,
                                                                         controllers,
                                                                         incident_waves)]))
    elif 'matrix_mode' in sim_params and not sim_params['matrix_mode']:
        # generate test arrays
        batch_params = [seeds,
                        physics_step,
                        door_state,
                        scale_factor,
                        battery_state,
                        mean_piston_position,
                        wave_dir,
                        incident_wave_height_points,
                        controllers,
                        incident_waves]
        shape = max(batch_params, key=len).shape
        for idx, param in enumerate(batch_params):
            if np.array(param).shape != shape:
                batch_params[idx] = to_shape(np.array(param), shape)
        batch_params = list(zip(*[np.array(param).ravel() for param in batch_params]))

    node.get_logger().info(f'Generated {len(batch_params)} simulation runs')
    node.get_logger().debug('PhysicsStep, PhysicsRTF, Seed, Duration, DoorState, ScaleFactor' +
                            ', BatteryState, MeanPistonPosition, WaveDir(deg/from)' +
                            ', IncidentWaveHeightPoints' +
                            ', UpperSpringParams, LowerSpringParams' +
                            ', Controller' +
                            ', IncWaveSpectrumType;IncWaveSpectrumParams')
    [node.get_logger().debug(f'{print_optional(ps)}, {print_optional(physics_rtf)}' +
                             f', {print_optional(sd)}, {duration}, {ds}, {sf}' +
                             f', {print_optional(bs)}' +
                             f', {print_optional(mpp)}' +
                             f', {print_optional(wd)}' +
                             f', {print_optional(ihp)}' +
                             f', {print_optional(SpringParams("upper", usp))}' +
                             f', {print_optional(SpringParams("lower", lsp))}' +
                             f', {print_optional(ctl)}' +
                             f', {print_optional(iw)}')
        for sd, ps, ds, sf, bs, mpp, wd, ihp, ctl, iw in batch_params]

    node.get_logger().info('Creating log file: ' +
                           os.path.join(batch_results_dir, 'batch_runs.log'))
    with open(os.path.join(batch_results_dir, 'batch_runs.log'), 'w') as fd:
        fd.write(f'# Generated {len(batch_params)} simulation runs\n')
        fd.write('RunIndex, SimReturnCode, StartTime, rosbag2Filename, pblogFilename' +
                 ', PhysicsStep, PhysicsRTF' +
                 ', Seed, Duration, DoorState, ScaleFactor, BatteryState' +
                 ', MeanPistonPosition, WaveDir(deg/from)' +
                 ', IncidentWaveHeightPoints' +
                 ', UpperSpringParams, LowerSpringParams' +
                 ', Controller' +
                 ', IncWaveSpectrumType;IncWaveSpectrumParams\n')

    # Find packages
    pkg_buoy_gazebo = get_package_share_directory('buoy_gazebo')
    pkg_buoy_description = get_package_share_directory('buoy_description')

    # Find model templates
    model_dir = 'mbari_wec_base'
    empy_base_sdf_file = os.path.join(pkg_buoy_description, 'models', model_dir, 'model.sdf.em')
    base_sdf_file = os.path.join(pkg_buoy_description, 'models', model_dir, 'model.sdf')

    model_dir = 'mbari_wec'
    empy_sdf_file = os.path.join(pkg_buoy_description, 'models', model_dir, 'model.sdf.em')
    sdf_file = os.path.join(pkg_buoy_description, 'models', model_dir, 'model.sdf')

    model_dir = 'mbari_wec_ros'
    empy_ros_sdf_file = os.path.join(pkg_buoy_description, 'models', model_dir, 'model.sdf.em')
    ros_sdf_file = os.path.join(pkg_buoy_description, 'models', model_dir, 'model.sdf')

    # Find world file template
    empy_world_file = os.path.join(pkg_buoy_gazebo, 'worlds', 'mbari_wec.sdf.em')
    world_file = os.path.join(pkg_buoy_gazebo, 'worlds', 'mbari_wec_batch.sdf')

    node.get_logger().info(f'rosbag2 recording enabled: {rosbag2}')

    # Start batch runs
    rng = np.random.default_rng()
    for idx, (sd, ps, ds, sf, bs, mpp, wd, ihp, ctl, iw) in enumerate(batch_params):
        if not rclpy.ok():
            break  # Shutting down
        seed = rng.integers(2**32-1) if sd==0 else sd
        node.get_logger().info(f'\n\nSim run [{idx}] for {duration} seconds:' +
                               f" seed='{sd}" +
                               f" door state='{ds}', scale factor={sf}" +
                               f", battery state={bs if bs is not None else 'None'}" +
                               f", mean piston position={mpp if mpp is not None else 'None'}" +
                               f", WaveDir(deg/from)={wd if wd is not None else 'default'}" +
                               f", IncidentWaveHeightPoints={ihp if ihp is not None else 'default'}" +
                               ', UpperSpringParams=' +
                               f"{str(SpringParams('upper', usp))}" +
                               ', LowerSpringParams=' +
                               f"{str(SpringParams('lower', lsp))}" +
                               f", controller={str(ctl) if ctl is not None else 'None'}" +
                               ', IncidentWaveSpectrumType=' +
                               f"{str(iw) if iw is not None else 'None'}\n")

        # fill mbari_wec_base model template with params
        empy(['-D', f"door_state = '{ds}'",
              '-o', base_sdf_file,
              empy_base_sdf_file])

        # fill mbari_wec world template with params
        mbari_wec_world_params = []
        if ps is not None:
            mbari_wec_world_params.extend(['-D', f'physics_step = {ps}'])
        if physics_rtf is not None:
            mbari_wec_world_params.extend(['-D', f'physics_rtf = {physics_rtf}'])
        mbari_wec_world_params.extend(['-o', world_file,
                                       empy_world_file])
        empy(mbari_wec_world_params)

        # fill mbari_wec_ros model template with params
        mbari_wec_ros_params = []
        if ihp is not None:
            mbari_wec_ros_params.extend(['-D', f'inc_wave_height_points = {ihp.points}'])
        mbari_wec_ros_params.extend(['-o', ros_sdf_file,
                                     empy_ros_sdf_file])
        node.get_logger().debug(mbari_wec_ros_params)
        empy(mbari_wec_ros_params)

        # fill mbari_wec model template with params
        mbari_wec_model_params = ['-D', f'scale_factor = {sf}']
        if seed is not None:
            mbari_wec_model_params.extend(['-D', f'inc_wave_seed = {seed}'])
        if bs is not None:
            if 'SoC' in batt_state_type:
                mbari_wec_model_params.extend(['-D', f'battery_soc = {bs}'])
            elif 'EMF' in batt_state_type:
                mbari_wec_model_params.extend(['-D', f'battery_emf = {bs}'])
        if mpp is not None:
            mbari_wec_model_params.extend(['-D', f'x_mean_pos = {mpp}'])
        if wd is not None:
            mbari_wec_model_params.extend(['-D', f'inc_wave_dir = {wd}'])
        if usp is not None:
            mbari_wec_model_params.extend(['-D', f'upper_polytropic_params = {usp.tolist()}'])
        if lsp is not None:
            mbari_wec_model_params.extend(['-D', f'lower_polytropic_params = {lsp.tolist()}'])
        if iw is not None:
            mbari_wec_model_params.extend(['-D', f'inc_wave_spectrum_type = "{iw.name}"'])
            if 'MonoChromatic' in iw.name:
                if iw.A is not None:
                    mbari_wec_model_params.extend(['-D', f'A = {iw.A}'])
                    mbari_wec_model_params.extend(['-D', f'T = {iw.T}'])
            if 'Bretschneider' in iw.name:
                if iw.Hs is not None:
                    mbari_wec_model_params.extend(['-D', f'Hs = {iw.Hs}'])
                    mbari_wec_model_params.extend(['-D', f'Tp = {iw.Tp}'])
                if iw.n_phases is not None:
                    mbari_wec_model_params.extend(['-D', f'n_phases = {int(iw.n_phases)}'])
                if iw.spreading_factor is not None:
                    mbari_wec_model_params.extend(['-D', f'spreading_factor = {iw.spreading_factor}'])
                elif iw.spreading_deg is not None:
                    # spreading_deg was explicitly 0 → no directional spreading
                    mbari_wec_model_params.extend(['-D', 'spreading_factor = None'])
            if 'Custom' in iw.name:
                if iw.f is not None:
                    mbari_wec_model_params.extend(['-D', f'f = {iw.f.tolist()}'])
                    mbari_wec_model_params.extend(['-D', f'Szz = {iw.Szz.tolist()}'])
        mbari_wec_model_params.extend(['-o', sdf_file,
                                       empy_sdf_file])
        node.get_logger().debug(mbari_wec_model_params)
        empy(mbari_wec_model_params)

        # convert duration to iterations
        if ps is None:
            step_size = DEFAULT_PHYSICS_MAX_STEP_SIZE
        else:
            step_size = ps
        iterations = int(round(duration / step_size))

        node.get_logger().debug('running gz-sim with gz_args:=' +
                                '-r' if enable_gui else '-rs' +
                                f' --iterations {iterations}')

        # Dynamically create launch file
        start_time = time.strftime("%Y%m%d%H%M%S")
        rosbag2_dir = 'rosbag2'
        pblog_dir = 'pblog'
        run_results_dir = f'results_run_{idx}_{start_time}'
        os.makedirs(os.path.join(batch_results_dir, run_results_dir))

        # get info from processes
        proc_start_info = ActiveProcInfoHandler()
        proc_exit_info = ActiveProcInfoHandler()

        # python workaround for 'ln -sf'
        if rosbag2:
            os.symlink(os.path.join(run_results_dir, rosbag2_dir),
                    os.path.join(batch_results_dir, f'latest_rosbag_{start_time}'), target_is_directory=True)
            os.replace(os.path.join(batch_results_dir, f'latest_rosbag_{start_time}'),
                    os.path.join(batch_results_dir, f'latest_rosbag'))

        def generate_launch_description():
            ld = []
            mbari_wec = IncludeLaunchDescription(
                PythonLaunchDescriptionSource(
                    os.path.join(pkg_buoy_gazebo, 'launch', 'mbari_wec.launch.py'),
                ),
                launch_arguments={'extra_gz_args': '-r' if enable_gui else '-rs' +
                                                   f' --iterations {iterations}',
                                  'world_file': 'mbari_wec_batch.sdf',
                                  'regenerate_models': 'false',
                                  'pbloghome': batch_results_dir,
                                  'pblogdir': os.path.join(run_results_dir, pblog_dir)}.items(),
            )

            # record all topics with rosbag2
            if rosbag2:
                rosbag2_proc = ExecuteProcess(
                    cmd=['ros2', 'bag', 'record', '-s', 'mcap',
                        '-o', os.path.join(batch_results_dir, run_results_dir, rosbag2_dir), '-a'],
                    output='screen'
                )
                ld.append(rosbag2_proc)

            ld.append(mbari_wec)
            ld.append(
                RegisterEventHandler(  # get info from processes
                    OnProcessStart(on_start=lambda info, unused: proc_start_info.append(info))
                )
            )
            ld.append(
                RegisterEventHandler(  # get return codes from processes
                    OnProcessExit(on_exit=lambda info, unused: proc_exit_info.append(info))
                )
            )

            if ctl is not None:
                pkg_ctl = get_package_share_directory(ctl.package)
                controller_launch = IncludeLaunchDescription(
                    PythonLaunchDescriptionSource(
                        os.path.join(pkg_ctl, 'launch', ctl.launch_file)
                    ),
                )
                ld.append(controller_launch)

            def capture_start_pids(info_, unused):
                proc_start_info.append(info_)
                start_procs = resolveProcesses(proc_start_info, process='gazebo')
                for info in [proc_start_info[item] for item in start_procs]:
                    print(f'{info.pid}')
                    print(f'{info.cmd}')
                    import subprocess
                    output = subprocess.run(['ps', 'h', '--ppid', f'{info.pid}', '-o', 'pid'])
                    print(f'{output.stdout}')
                    print(f'{output.stderr}')

            return LaunchDescription(ld)

        # Launch sim instance
        ls = LaunchService()
        ls.include_launch_description(generate_launch_description())
        result = ls.run()

        if result != 0:
            node.get_logger().error(f'Simulation run [{idx}] was not successful: ' +
                                    f'batch launch return code [{result}]')

        # get return codes from processes
        procs = resolveProcesses(proc_exit_info, process='gazebo')
        gzsim_result = 0
        for info in [proc_exit_info[item] for item in procs]:
            gzsim_result = info.returncode
            if gzsim_result != 0:
                node.get_logger().error(f'Simulation run [{idx}] was not successful: ' +
                                        f'gz-sim return code [{gzsim_result}]')
                result = gzsim_result
                if info.returncode < -2:
                    node.get_logger().error(f'gz sim process may still be running...')
                    start_procs = resolveProcesses(proc_start_info, process='gazebo')
                    for info in [proc_start_info[item] for item in start_procs]:
                        for proc in ['ruby', 'sim_pblog']:
                            # kill whole process tree
                            # kill_proc = 'ps x -o "%r %c"' \
                            #             + f' | grep {proc}' \
                            #             + ' | cut -d " " -f 2' \
                            #             + ' | xargs -I{} kill -9 -- -{}'

                            # kill just process
                            kill_proc = 'ps x -o "%p %c"' \
                                        + f' | grep {proc}' \
                                        + " | awk '{ print $1 }'" \
                                        + ' | xargs -I{} kill -9 {}'

                            output = subprocess.run(kill_proc, shell=True, check=True)
                            print(f'{output.args}')

        # Write to log
        with open(os.path.join(batch_results_dir, 'batch_runs.log'), 'a') as fd:
            fd.write(f'{idx}, {result}, {start_time}' +
                     f', {os.path.join(run_results_dir, rosbag2_dir)}' + #Left unchanged to match previous system, potential #TODO
                     f', {os.path.join(run_results_dir, pblog_dir)}' +
                     f', {print_optional(ps)}, {print_optional(physics_rtf)}' +
                     f', {print_optional(seed)}, {duration}, {ds}, {sf}' +
                     f', {print_optional(bs)}' +
                     f', {print_optional(mpp)}' +
                     f', {print_optional(wd)}' +
                     f', {print_optional(ihp)}' +
                     f', {print_optional(SpringParams("upper", usp))}' +
                     f', {print_optional(SpringParams("lower", lsp))}' +
                     f', {print_optional(ctl)}' +
                     f', {print_optional(iw)}\n')

    # Return all files to defaults
    empy(['-o', base_sdf_file,
          empy_base_sdf_file])
    empy(['-o', world_file,
          empy_world_file])
    empy(['-o', ros_sdf_file,
          empy_ros_sdf_file])
    empy(['-o', sdf_file,
          empy_sdf_file])


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Batch running for mbari_wec_gz')
    parser.add_argument('sim_params_yaml',
                        help='yaml file with batch parameters')
    parser.add_argument('--rosbag2',
                    default='true',
                    help='Enable rosbag2 recording (true/false)')
    args, unknown = parser.parse_known_args()
    generate_simulations(args.sim_params_yaml, rosbag2=args.rosbag2.lower() == 'true')
